<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fdl</string>
		<string>fidl</string>
	</array>
	<key>name</key>
	<string>Franca IDL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#lex</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.toc-list.banner.block.fidl</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*/\* =(\s*.*?)\s*= \*/$\n?</string>
					<key>name</key>
					<string>comment.block.fidl</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*&lt;\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.fidl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*&gt;</string>
					<key>name</key>
					<string>comment.block.fidl</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.fidl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.fidl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\*/(?=[^*].*\n)</string>
					<key>name</key>
					<string>invalid.illegal.stray-comment-end.fidl</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.toc-list.banner.line.fidl</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*// =(\s*.*?)\s*=\s*$\n?</string>
					<key>name</key>
					<string>comment.line.banner.fidl</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*//</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.fidl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?&lt;=^|[^\\])\s*(?=\n)$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.fidl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#lex-continuation</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>lex</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#lex-keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lex-constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lex-string</string>
				</dict>
			</array>
		</dict>
		<key>lex-constant</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.language.fidl</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(NULL|true|false|TRUE|FALSE)\b</string>
				</dict>
			</array>
		</dict>
		<key>lex-continuation</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.line-continuation.fidl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.deprecated.space-after-continuation.fidl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\\)(?:$\n?|(\s+?)(?=\n)$)</string>
			<key>name</key>
			<string>punctuation.separator.continuation.fidl</string>
		</dict>
		<key>lex-keyword</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.fidl</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*\b(sizeof|(?:__|(?!\w+__))typeof(?:__)?)\b</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.fidl</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*\b((?:__|(?!\w+__))asm(?:__)?|version|attribute|method|in|out|broadcast|selective|import|model|error|typedef|is)\b</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.fidl</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*\b(Int8|Int16|Int32|UInt8|UInt16|UInt32|UInt64|Int64|Boolean|String|major|Double|Float|minor|int|readonly|short|signed|unsigned|void)\b</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.fidl</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*\b(extern|static|register|__attribute__|(?:__|(?!\w+__))(?:const|restrict|volatile|inline)(?:__)?)\b</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.fidl</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*\b(interface|struct|union|enumeration|package|typeCollection)\b</string>
				</dict>
			</array>
		</dict>
		<key>lex-number</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.fidl</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*(\b(0[xX][0-9a-fA-F]*|0[0-7]*|[1-9][0-9]*)[uU]?(ll?|LL?)?\b)</string>
				</dict>
			</array>
		</dict>
		<key>lex-string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.fidl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(")|(?&lt;=^|[^\\])\s*(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.fidl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unexpected-end-of-line.fidl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.fidl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#lex-continuation</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string_escaped_char</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string_placeholder</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.fidl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(')|(?&lt;=^|[^\\])\s*(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.fidl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unexpected-end-of-line.fidl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.fidl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#lex-continuation</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string_escaped_char</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.fidl</string>
	<key>uuid</key>
	<string>7b6518cc-e0eb-4d96-bd61-5493816e0279</string>
</dict>
</plist>
